site_name: OE4M74 Lab Documentation
site_description: Learn important machine learning concepts hands-on Python code.
site_url: https://ARGF0RCE.github.io/OE4M74-Lab

repo_url: https://github.com/ARGF0RCE/OE4M74-Lab
repo_name: ARGF0RCE/OE4M74-Lab

theme:
  name: material
  logo: assets/iiitdmj-logo.jpg
  favicon: assets/iiitdmj-logo.jpg
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

nav:
  - Home: 'index.md'
  - Local Setup: 'setup.md'
  - 00. Getting Started with Python: 'Introduction_to_Python_Programming.ipynb'
  - 01. Data Processing Data representation and visualization: 'Data_Processing_Data_representation_and_visualization.ipynb'
  - 01.01 Data Processing and EDA with IRIS Dataset: 'Data_Processing_and_EDA_with_IRIS_Dataset.ipynb'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARGF0RCE/OE4M74-Lab
